
TYPES: BEGIN OF ty_mara,

  MATNR TYPE MARA-MATNR,
  ERSDA TYPE MARA-ERSDA,
  ERNAM TYPE MARA-ERNAM,
  LAEDA TYPE MARA-LAEDA,
  VPSTA TYPE MARA-VPSTA,

  END OF ty_mara.

TYPES: BEGIN OF ty_mard,

   MATNR TYPE MARD-MATNR,
   WERKS TYPE MARD-WERKS,
   LGORT TYPE MARD-LGORT,

  END OF ty_mard.

TYPES: BEGIN OF ty_kna1,

  KUNNR TYPE KNA1-KUNNR,
  NAME1 TYPE KNA1-NAME1,
  STCD2 TYPE KNA1-STCD2,
  ORT01 type KNA1-ORT01,
  TXJCD TYPE KNA1-TXJCD,

  END OF ty_kna1.



DATA: V_TESTE(10) TYPE C,
      V_MATNR TYPE MARA-MATNR,
      V_MARA2 TYPE MATNR.

DATA: WA_MARA TYPE MARA.
DATA: WA_KNA1 TYPE KNA1.

DATA: C_X TYPE C VALUE 'X'.

*DATA: GT_MARA TYPE STANDARD TABLE OF ty_mara.
*DATA: GT_MARD TYPE STANDARD TABLE OF ty_mard.
DATA: GT_KNA1 TYPE STANDARD TABLE OF ty_kna1.


*SELECT * FROM MARA
*  INTO TABLE GT_MARA
*  WHERE MATNR = '0000-0037-0'.

SELECT SINGLE * FROM KNA1
  INTO WA_KNA1
  WHERE KUNNR = '0002000023'.


*SELECT MATNR ERSDA ERNAM LAEDA VPSTA FROM MARA
*  INTO TABLE GT_MARA
*  WHERE MATNR = '0000-0037-0'.
*
*SELECT MATNR WERKS LGORT FROM MARD
*  INTO TABLE GT_MARD
*  WHERE WERKS = 'RJ64'
*  OR WERKS = 'RJ65'.

SELECT KUNNR NAME1 STCD2 ORT01 TXJCD FROM KNA1
  INTO TABLE GT_KNA1
  WHERE KUNNR = '0020000070'
  OR    KUNNR = '0900000031'
  OR    KUNNR = '0002000023'.
  




BREAK-POINT.
